# Generated by Django 3.0.6 on 2020-05-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Osakkeet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=64)),
                ('maara', models.IntegerField(default=1)),
                ('alkuarvo', models.IntegerField(default=1)),
                ('arvo', models.IntegerField(default=1)),
                ('osingot', models.IntegerField(default=1)),
                ('salkunarvo', models.IntegerField(default=1)),
                ('salkunverot', models.IntegerField(default=1)),
                ('verovuosi', models.IntegerField(default=2010)),
            ],
        ),
    ]
